package com.pinetechs.orvix.ims.user.enums;

public enum PermissionCode {
    COMPANY_VIEW,
    COMPANY_CREATE,
    COMPANY_UPDATE,
    COMPANY_DISABLE,

    USER_VIEW,
    USER_CREATE,
    USER_UPDATE,
    USER_DISABLE,
    USER_RESET_PASSWORD,

    VEHICLE_TASK_VIEW,
    VEHICLE_TASK_CREATE,
    VEHICLE_TASK_UPDATE,
    VEHICLE_TASK_ASSIGN_USERS,
    VEHICLE_TASK_CLOSE,
    VEHICLE_REPORT_VIEW,

    ASSET_TASK_VIEW,
    ASSET_TASK_CREATE,
    ASSET_TASK_UPDATE,
    ASSET_TASK_ASSIGN_USERS,
    ASSET_TASK_CLOSE,
    ASSET_REPORT_VIEW,

    SPARE_PART_TASK_VIEW,
    SPARE_PART_TASK_CREATE,
    SPARE_PART_TASK_UPDATE,
    SPARE_PART_TASK_ASSIGN_USERS,
    SPARE_PART_TASK_CLOSE,
    SPARE_PART_REPORT_VIEW,

    MOBILE_TASK_LIST,
    MOBILE_SCAN_CREATE,
    MOBILE_QUANTITY_ENTRY,
    MOBILE_LOCATION_CHANGE
}
